// Code generated by xgen-plus. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// "SimpleType"
// base:"xs:Name"
// TAcsiName ...
type TAcsiName string

// "SimpleType"
// base:"tAcsiName"
// TIEDNameIsNone ...
type TIEDNameIsNone string

// "SimpleType"
// TIEDNameOrNone ...
type TIEDNameOrNone struct { /* UNION */
	TIEDName       *TIEDName
	TIEDNameIsNone *string
}

// "SimpleType"
// base:"tAcsiName"
// TIEDName ...
type TIEDName string

// "ComplexType"
// ComplexType1 ...
type ComplexType1 struct {
	NodeID
	Content  *TIEDNameOrNone `xml:",chardata" json:",omitempty"`
	TypeAttr string          `xml:"type,attr" json:"type"`
}

// "ComplexType"
// TBaseElement ...
type TBaseElement struct {
	NodeID
	AdditionalFields AdditionalFieldsType `xml:",any,attr"`
	CustomElements   []AnyHolder          `xml:",any"`
	Text             string               `xml:"Text" json:"Text"`
}
