// Code generated by xgen-plus. DO NOT EDIT.

package schema

import (
	"encoding/xml"
)

// "AttributeGroup"
// AgDesc ...
type AgDesc struct {
	DescAttr string `xml:"desc,attr,omitempty" json:"desc,omitempty"`
}

// "ComplexType"
// TBaseElement ...
type TBaseElement struct {
	NodeID
	AdditionalFields AdditionalFieldsType `xml:",any,attr"`
	CustomElements   []AnyHolder          `xml:",any"`
}

// "ComplexType"
// TUnNaming ...
type TUnNaming struct {
	TBaseElement
	AgDesc // AttributeGroup
}

// "ComplexType"
// TNaming ...
type TNaming struct {
	TBaseElement
	AgDesc         // AttributeGroup
	NameAttr TName `xml:"name,attr" json:"name"`
}

// "SimpleType"
// base:"tAnyName"
// TName ...
type TName string

// "SimpleType"
// base:"xs:normalizedString"
// TAnyName ...
type TAnyName string
